### ISSUE TITLE
Revisar estas lineas de gitignore

### ISSUE THREAD

**Issue by juan-rojo** [oscarperpinan/prueba_github_ice#3]
Tiene pinta de estar mal esto:
https://github.com/oscarperpinan/prueba_github_ice/blob/ea1674458ac2dce7e3207bcbcf8abad92fd6ab8d/.gitignore#L15-L17

**Comment by oscarperpinan** [comment]
Gracias por el aviso. Lo revisaré.

**Comment by oscarperpinan** [comment]
Ya lo he revisado. Está todo correcto. Gracias.
